Tests for adding podcast API
gpodder/mygpo pull request #336
Opened 2020-01-17 12:19 UTC by SiqingYu

See https://github.com/gpodder/mygpo/issues/219 for more info.

2020-01-18 10:16 UTC, stefankoegl commented
As mentioned in the online comment, the tests never actually test the task result - just the fact that the task exists. You can look into https://docs.celeryproject.org/projects/django-celery/en/2.4/cookbook/unit-testing.html#using-a-custom-test-runner-to-test-with-celery on how to easily test task results. An alternative approach is described in https://medium.com/@erayerdin/how-to-test-celery-in-django-927438757daf

2020-01-18 10:16 UTC, stefankoegl requested changes

2020-01-18 10:16 UTC, stefankoegl commented on mygpo/api/tests.py
> +        self.assertEqual(status_resp.json().get('status'), 'pending')
If I understand this test correctly, it only tests whether a task has been started - but not its result.

2020-01-18 20:10 UTC, SiqingYu commented on mygpo/api/tests.py
> +        self.assertTrue(result.ready())
@stefankoegl
I add these to test the Celery task result.
Celery testing is particularly tricky. I've tried the two references you provided but could get neither pytest fixture or pytest-django working for Celery. I turn to celery.app.task.Task.apply() to execute the task ad-hoc.
The problem is that the Celery instance is the one from mygpo.celery, the same as the real one, thus accessing the production database. I think this is a potential problem. But I can't find a better solution at the moment.
Any suggestion is appreciated. :smile:

2020-01-18 20:11 UTC, SiqingYu commented on mygpo/api/tests.py
> +        self.assertEqual(status_resp.json().get('status'), 'pending')
@stefankoegl
I add tests for the Celery task result below.
Celery testing is particularly tricky. I've tried the two references you provided but could get neither pytest fixture or pytest-django working for Celery. I turn to celery.app.task.Task.apply() to execute the task ad-hoc.
The problem is that the Celery instance is the one from mygpo.celery, the same as the real one, thus accessing the production database. I think this is a potential problem. But I can't find a better solution at the moment.
Any suggestion is appreciated. :smile:

2020-01-18 20:30 UTC, stefankoegl commented on mygpo/api/tests.py
> +        self.assertEqual(status_resp.json().get('status'), 'pending')
> The problem is that the Celery instance is the one from mygpo.celery, the same as the real one, thus accessing the production database.

When running tests, the DATABASE setting is initialized to point to the test database (see https://docs.djangoproject.com/en/dev/topics/testing/overview/#the-test-database). Therefore I don't think its possible to access the prod database through `mygpo.celery` from within a test. These two should be completely isolated from each other.

2020-01-19 04:12 UTC, SiqingYu commented
Does the new PR for testing meet the requirement? If so, I'll move on to documentation and hopefully close the issue. :smile:

2020-01-19 04:13 UTC, SiqingYu commented on mygpo/api/tests.py
> +        self.assertEqual(status_resp.json().get('status'), 'pending')
@stefankoegl Does the new PR for testing meet the requirement? If so, I'll move on to documentation and hopefully close the issue. :smile:

2020-01-19 11:07 UTC, stefankoegl requested changes

2020-01-19 11:07 UTC, stefankoegl commented on mygpo/api/tests.py
> +        result = update_podcasts.apply(task_id=job_id)
Could you add a comment describing what this does exactly? That might not be obvious for somebody reading the code in the future.

2020-01-19 11:07 UTC, stefankoegl commented on mygpo/api/tests.py
> +        self.assertTrue(result.ready())
I think we're still not testing the end result. Now the test checks whether the task has completed, but what we actually want to achieve is to have a new podcast. I think that the checks should verify that a podcast with the submitted URL has been created.

2026-07-17 14:09 UTC, closed without merging